#!/bin/bash
#
# Linux SSH Hardening Module for CyberPatriot
#
# This script hardens OpenSSH configuration for Ubuntu 24.04 and Mint 21:
# 1. Creates hardened SSH configuration drop-in file
# 2. Sets security banner
# 3. Corrects file and directory permissions
# 4. Hardens moduli (removes weak DH groups <3071 bits)
# 5. Configures UFW firewall for SSH port
# 6. Validates and reloads SSH service
#
# Requirements:
#   - Root/sudo privileges
#   - OpenSSH server installed
#   - UFW firewall (optional but recommended)
#
# Supports: Ubuntu 24.04, Linux Mint 21

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINUX_DIR="$(dirname "$SCRIPT_DIR")"
LOG_PREFIX="[SSHHardening]"

# ====== CONFIGURATION ======
SSH_PORT="22"                      # Default SSH port (change if rubric requires)
KEEP_PORT_22_OPEN="yes"            # Keep port 22 open in UFW ("yes" or "no")
ENABLE_UFW="yes"                   # Enable UFW firewall ("yes" or "no")
HARDEN_MODULI="yes"                # Remove weak DH groups ("yes" or "no")
BANNER_TEXT='Authorized use only. Activity may be monitored and reported.'
CONFIG_NAME="99-cyberpatriot.conf"
TARGET_USER="${SUDO_USER:-${USER:-root}}"  # User to prep ~/.ssh for
ALLOW_USERS=""                     # Space-separated list of allowed users (empty = all)
# ===========================

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# Logging functions
log_info() {
    echo -e "${CYAN}${LOG_PREFIX} [INFO]${NC} $*"
}

log_ok() {
    echo -e "${GREEN}${LOG_PREFIX} [OK]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}${LOG_PREFIX} [WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}${LOG_PREFIX} [ERROR]${NC} $*"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Check if OpenSSH is installed
check_openssh() {
    if ! command -v sshd &> /dev/null; then
        # Try common paths
        if [[ -f /usr/sbin/sshd ]]; then
            export PATH="/usr/sbin:/sbin:$PATH"
        else
            log_error "OpenSSH server (sshd) is not installed"
            exit 1
        fi
    fi
    log_info "OpenSSH server detected"
}

# Detect OS version
detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        log_info "Detected: $NAME $VERSION"

        # Check for supported OS
        if [[ "$ID" == "ubuntu" && "$VERSION_ID" == "24.04" ]]; then
            log_ok "Supported OS: Ubuntu 24.04"
            return 0
        elif [[ "$ID" == "linuxmint" && "$VERSION_ID" == "21" ]]; then
            log_ok "Supported OS: Linux Mint 21"
            return 0
        elif [[ "$ID" == "ubuntu" || "$ID" == "linuxmint" ]]; then
            log_warn "OS detected but version may not be tested ($NAME $VERSION)"
            return 0
        else
            log_warn "Unsupported OS: $NAME $VERSION (continuing anyway)"
            return 0
        fi
    else
        log_warn "Cannot detect OS version, proceeding with caution"
        return 0
    fi
}

# Create hardened SSH configuration
create_hardened_config() {
    log_info "Creating hardened SSH configuration..."

    mkdir -p /etc/ssh/sshd_config.d

    # Build AllowUsers line
    local allow_users_line="# AllowUsers not set (all users allowed)"
    if [[ -n "$ALLOW_USERS" ]]; then
        allow_users_line="AllowUsers ${ALLOW_USERS}"
    fi

    # Create drop-in config file
    cat > /etc/ssh/sshd_config.d/"$CONFIG_NAME" <<EOF
# === CyberPatriot SSH Hardening (automated) ===
# Generated by Linux SSH Hardening Module
# Protocol 1 is removed in modern OpenSSH; Protocol 2 is implicit

Port ${SSH_PORT}

# Logging
SyslogFacility AUTHPRIV
LogLevel VERBOSE

# Security settings
StrictModes yes
UseDNS no
VersionAddendum none

# Authentication
PermitRootLogin no
PermitEmptyPasswords no
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitUserEnvironment no
UsePAM yes

# Forwarding and tunneling (disabled for security)
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
GatewayPorts no
PermitTunnel no

# Connection settings
LoginGraceTime 30
MaxAuthTries 3
MaxSessions 2
ClientAliveInterval 300
ClientAliveCountMax 2
TCPKeepAlive no

# Host-based authentication (disabled)
IgnoreRhosts yes
HostbasedAuthentication no

# Key and banner settings
AuthorizedKeysFile .ssh/authorized_keys
Banner /etc/issue.net
PrintMotd no
PrintLastLog yes

# Strong cryptographic algorithms (compatible with Ubuntu 24/Mint 21)
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# SFTP subsystem
Subsystem sftp internal-sftp

# User restrictions
${allow_users_line}
EOF

    chmod 0644 /etc/ssh/sshd_config.d/"$CONFIG_NAME"
    log_ok "Created hardened SSH configuration: /etc/ssh/sshd_config.d/$CONFIG_NAME"
}

# Create security banner
create_banner() {
    log_info "Creating security banner..."

    printf '%s\n' "$BANNER_TEXT" > /etc/issue.net
    chmod 0644 /etc/issue.net

    log_ok "Security banner created: /etc/issue.net"
}

# Fix SSH directory and file permissions
fix_permissions() {
    log_info "Fixing SSH directory and file permissions..."

    # System SSH directory
    if [[ -d /etc/ssh ]]; then
        chown -R root:root /etc/ssh
        chmod 0755 /etc/ssh 2>/dev/null || true

        # Config files
        shopt -s nullglob
        for conf_file in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf; do
            if [[ -e "$conf_file" ]]; then
                chmod 0644 "$conf_file"
            fi
        done

        # Host keys (private)
        for key_file in /etc/ssh/ssh_host_*_key; do
            if [[ -e "$key_file" ]]; then
                chmod 0600 "$key_file"
            fi
        done

        # Host keys (public)
        for pub_file in /etc/ssh/ssh_host_*_key.pub; do
            if [[ -e "$pub_file" ]]; then
                chmod 0644 "$pub_file"
            fi
        done
        shopt -u nullglob

        log_ok "System SSH permissions corrected"
    else
        log_warn "/etc/ssh directory not found"
    fi

    # User SSH directory (if target user exists)
    if getent passwd "$TARGET_USER" &>/dev/null; then
        local user_home
        user_home="$(getent passwd "$TARGET_USER" | cut -d: -f6)"

        if [[ -n "$user_home" && -d "$user_home" ]]; then
            # Create .ssh directory if it doesn't exist
            if [[ ! -d "$user_home/.ssh" ]]; then
                install -d -m 700 -o "$TARGET_USER" -g "$TARGET_USER" "$user_home/.ssh"
                log_ok "Created $user_home/.ssh directory"
            else
                chmod 700 "$user_home/.ssh"
                chown "$TARGET_USER:$TARGET_USER" "$user_home/.ssh"
            fi

            # Fix authorized_keys if it exists
            if [[ -f "$user_home/.ssh/authorized_keys" ]]; then
                chmod 600 "$user_home/.ssh/authorized_keys"
                chown "$TARGET_USER:$TARGET_USER" "$user_home/.ssh/authorized_keys"
                log_ok "Fixed permissions for $user_home/.ssh/authorized_keys"
            fi

            log_ok "User SSH permissions corrected for: $TARGET_USER"
        fi
    else
        log_warn "Target user '$TARGET_USER' not found, skipping user SSH directory"
    fi
}

# Harden moduli (remove weak DH groups)
harden_moduli() {
    if [[ "$HARDEN_MODULI" != "yes" ]]; then
        log_info "Moduli hardening skipped (disabled in config)"
        return 0
    fi

    log_info "Hardening moduli (removing DH groups < 3071 bits)..."

    if [[ ! -f /etc/ssh/moduli ]]; then
        log_warn "/etc/ssh/moduli not found, skipping"
        return 0
    fi

    # Keep only groups >= 3071 bits (5th field)
    local original_count
    local new_count

    original_count=$(wc -l < /etc/ssh/moduli)

    awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe

    if [[ -s /etc/ssh/moduli.safe ]]; then
        new_count=$(wc -l < /etc/ssh/moduli.safe)
        mv /etc/ssh/moduli.safe /etc/ssh/moduli
        chmod 0644 /etc/ssh/moduli

        local removed=$((original_count - new_count))
        log_ok "Moduli hardened: kept $new_count groups, removed $removed weak groups"
    else
        rm -f /etc/ssh/moduli.safe
        log_warn "No strong moduli found (>=3071 bits), keeping original file"
    fi
}

# Configure UFW firewall
configure_firewall() {
    if [[ "$ENABLE_UFW" != "yes" ]]; then
        log_info "UFW configuration skipped (disabled in config)"
        return 0
    fi

    if ! command -v ufw &> /dev/null; then
        log_warn "UFW not installed, skipping firewall configuration"
        return 0
    fi

    log_info "Configuring UFW firewall..."

    # Allow SSH port
    ufw allow "${SSH_PORT}/tcp" comment 'SSH' &>/dev/null || true
    log_ok "UFW: Allowed port ${SSH_PORT}/tcp"

    # Handle port 22 if different from SSH_PORT
    if [[ "$SSH_PORT" != "22" && "$KEEP_PORT_22_OPEN" == "no" ]]; then
        # Try to remove port 22 rule
        ufw delete allow 22/tcp &>/dev/null || true
        log_info "UFW: Removed port 22/tcp rule (SSH moved to port ${SSH_PORT})"
    fi

    # Enable UFW (will prompt if not already enabled)
    if ! ufw status | grep -q "Status: active"; then
        log_info "Enabling UFW firewall..."
        yes | ufw enable &>/dev/null || true
        log_ok "UFW firewall enabled"
    else
        log_info "UFW already active"
    fi

    # Show status
    log_info "UFW status:"
    ufw status numbered | grep -E "(Status|${SSH_PORT})" || true
}

# Validate SSH configuration
validate_config() {
    log_info "Validating SSH configuration..."

    if sshd -t 2>&1; then
        log_ok "SSH configuration is valid"
        return 0
    else
        log_error "SSH configuration validation failed!"
        return 1
    fi
}

# Reload SSH service
reload_ssh_service() {
    log_info "Reloading SSH service..."

    local service_name=""

    # Detect service name
    if systemctl list-unit-files | grep -q '^ssh\.service'; then
        service_name="ssh"
    elif systemctl list-unit-files | grep -q '^sshd\.service'; then
        service_name="sshd"
    elif command -v service &> /dev/null; then
        # Fallback to service command
        if service ssh status &>/dev/null; then
            service_name="ssh"
        elif service sshd status &>/dev/null; then
            service_name="sshd"
        fi
    fi

    if [[ -z "$service_name" ]]; then
        log_error "Cannot detect SSH service name"
        return 1
    fi

    # Reload service
    if command -v systemctl &> /dev/null; then
        systemctl reload "$service_name"
        log_ok "SSH service reloaded"

        # Show status
        systemctl status "$service_name" --no-pager --lines=0 || true
    elif command -v service &> /dev/null; then
        service "$service_name" reload
        log_ok "SSH service reloaded"
    fi
}

# Display configuration summary
display_summary() {
    echo ""
    echo -e "${BOLD}${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║                SSH Hardening Complete                     ║${NC}"
    echo -e "${BOLD}${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}Configuration Summary:${NC}"
    echo -e "  ${GREEN}✓${NC} SSH Port: ${BOLD}${SSH_PORT}${NC}"
    echo -e "  ${GREEN}✓${NC} Root Login: ${BOLD}no${NC}"
    echo -e "  ${GREEN}✓${NC} Password Authentication: ${BOLD}no${NC}"
    echo -e "  ${GREEN}✓${NC} Empty Passwords: ${BOLD}no${NC}"
    echo -e "  ${GREEN}✓${NC} Public Key Authentication: ${BOLD}yes${NC}"
    echo -e "  ${GREEN}✓${NC} X11 Forwarding: ${BOLD}no${NC}"
    echo -e "  ${GREEN}✓${NC} TCP Forwarding: ${BOLD}no${NC}"
    echo -e "  ${GREEN}✓${NC} Max Auth Tries: ${BOLD}3${NC}"
    echo -e "  ${GREEN}✓${NC} Max Sessions: ${BOLD}2${NC}"
    echo -e "  ${GREEN}✓${NC} Strong Ciphers: ${BOLD}enabled${NC}"
    echo -e "  ${GREEN}✓${NC} Security Banner: ${BOLD}enabled${NC}"

    if [[ -n "$ALLOW_USERS" ]]; then
        echo -e "  ${GREEN}✓${NC} Allowed Users: ${BOLD}${ALLOW_USERS}${NC}"
    fi

    if [[ "$ENABLE_UFW" == "yes" ]]; then
        echo -e "  ${GREEN}✓${NC} UFW Firewall: ${BOLD}configured${NC}"
    fi

    echo ""

    # Show effective settings (key items)
    log_info "Effective SSH configuration (key settings):"
    sshd -T 2>/dev/null | grep -E '^(port|maxauthtries|maxsessions|permitrootlogin|pubkeyauthentication|passwordauthentication|permitemptypasswords|x11forwarding|allowtcpforwarding|loglevel)' | sed 's/^/  /' || true
}

# Main execution
main() {
    log_info "Linux SSH Hardening Module starting..."
    echo ""

    # Pre-flight checks
    check_root
    detect_os
    check_openssh

    echo ""

    # Step 1: Create hardened configuration
    create_hardened_config

    echo ""

    # Step 2: Create security banner
    create_banner

    echo ""

    # Step 3: Fix permissions
    fix_permissions

    echo ""

    # Step 4: Harden moduli
    harden_moduli

    echo ""

    # Step 5: Configure firewall
    configure_firewall

    echo ""

    # Step 6: Validate configuration
    if ! validate_config; then
        log_error "Configuration validation failed, not reloading SSH"
        exit 1
    fi

    echo ""

    # Step 7: Reload SSH service
    reload_ssh_service

    echo ""

    # Step 8: Display summary
    display_summary

    echo ""
    log_ok "SSH Hardening Module completed successfully"
}

# Run main function
main "$@"
